version: '3'

services:
  nginx:
    build: ./docker/nginx
    networks:
      manager:
        aliases:
          - nginx
          - manager.hm
    ports:
      - ${PUB_HTTP_PORT}:80
      - ${PUB_HTTPS_PORT}:443
    volumes:
      - ./docker/nginx/ssl:/etc/nginx/ssl

networks:
  manager: